#123 [로그인] 자동 로그인 기능 추가
mash-up-kr/SulSul-Android pull request #132
Opened 2023-08-01 18:27 UTC by SEO-J17

+ isValidate로 super.onCreate 전에 체크해서 로그인 화면을 띄울지 홈으로 갈지 정합니당~

2023-08-02 01:07 UTC, oreocube approved these changes
야호 자동로그인

2023-08-02 01:07 UTC, oreocube commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/login/LoginActivity.kt
> +        }
isValidate를 리턴하는 함수로 빼도 좋을 것 같아~! 그리고 setContent 전에 바로 홈으로 이동시키면 밑에서 체크 안해도 될 것 같은데 ? 아닌감..?

2023-08-02 05:40 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/login/LoginActivity.kt
> +        }
아 마자마자 그래도 돼 근데 LoginScreen을 두번 쓰기 싫어서 저렇게 한건데 isValidate로 하는게 오히려 더 별로일가..? 진쫘 별로인거 같긴햌ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 차라리 LoginScreen을 컴포저블 함수로 빼서 사용할까?

2023-08-02 06:37 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/login/LoginActivity.kt
> +        }
아 지혜야 방금 깨달았다.. 너 말이 맞는거 같아 저거 home으로 가는 로직만 있으면 굳이 isValidate를 안해도 되겠네.. 멋졍.

2023-08-02 14:24 UTC, AnKyungMoo requested changes
일단 정지

2023-08-03 15:22 UTC, oreocube reviewed
이거 내가 내일 좀더 봐도 될까?

2023-08-03 15:22 UTC, oreocube commented on presentation/src/main/AndroidManifest.xml
> +            android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
우리 기본 테마가 상태바 투명이라 이렇게 하면 배터리 같은거 표시 안될듯
```suggestion
WindowCompat.setDecorFitsSystemWindows(window, false)
```

2023-08-03 15:22 UTC, oreocube commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +                ) {
이거 없어도 될것같은뎅?

2023-08-03 15:22 UTC, oreocube commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashScreen.kt
> +            ),
요거. 스크린 사이즈던데 FillBounds쓰면 해상도에 따라 찌그러져ㅠ 피그마 보니까 왜 통으로 넣었는지는 알겠지만,, 크롭이 나을 것 같아

https://developer.android.com/jetpack/compose/graphics/images/customize

<img width="828" alt="스크린샷 2023-08-04 오전 12 18 11" src="https://github.com/mash-up-kr/SulSul-Android/assets/78132126/a53421de-defc-4cc7-963d-105148f919bd">
<img width="837" alt="스크린샷 2023-08-04 오전 12 18 57" src="https://github.com/mash-up-kr/SulSul-Android/assets/78132126/540d11c1-abd8-4e1f-a8c4-81aff230f7c1">

2023-08-03 19:37 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashScreen.kt
> +            ),
아 오키오키 수정할게! crop이 낫겠다!!

2023-08-03 19:37 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +                ) {
움 다른 액티비티들은 다 있는데 얘만 없어도 되는이유가 있을까??

2023-08-03 19:37 UTC, SEO-J17 commented on presentation/src/main/AndroidManifest.xml
> +            android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
맞아 그러더라구..! 다시 수정했엉!!

2023-08-03 21:22 UTC, oreocube commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +                ) {
?? 로그인만 Surface 있고 나머지는 다 AlcoholFreeAndroidTheme 안에 XxxScreen만 있는 형태 아냐?

2023-08-04 09:05 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +                ) {
와이씨 진짜네 나저거 필수로 있어야 되는건줄 알았어..ㅎ 수정 할겡~ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-08-04 15:03 UTC, AnKyungMoo reviewed
코멘트 남겼다

2023-08-04 15:03 UTC, AnKyungMoo commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +        }
이거 함수로 분리해서 onCreate에는 함수만 호출하도록 하자.
onCreate에 로직 여러개 있으면 정신업서

2023-08-04 15:03 UTC, AnKyungMoo commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +        WindowCompat.setDecorFitsSystemWindows(window, false)
```suggestion
        installSplashScreen()
        super.onCreate(savedInstanceState)
        
        WindowCompat.setDecorFitsSystemWindows(window, false)
```

Nit: 엔터 불편하네요

그리고 installSplashScreen은 super.onCreate()보다 먼저 호출되어야하나보네..!

2023-08-04 15:04 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +        }
넹넹 알겠습니당

2023-08-04 15:05 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +        WindowCompat.setDecorFitsSystemWindows(window, false)
마자용 먼저 호출되어야 한대용 엔터 고칠게욬ㅋㅋㅋㅋㅋㅋㅋㅋ

2023-08-04 15:22 UTC, AnKyungMoo commented on presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/splash/SplashActivity.kt
> +        WindowCompat.setDecorFitsSystemWindows(window, false)
암이 낳앗습미다

2023-08-04 15:22 UTC, AnKyungMoo approved these changes
좋았다~

2023-08-04 15:23 UTC, merged