#7 로그인 토큰 저장
mash-up-kr/SulSul-Android pull request #8
Opened 2023-05-23 06:00 UTC by SEO-J17

데이터 스토어 preference를 이용하여 토큰 값 저장하고 get해 오는 기능 구현했습니다!

2023-05-24 17:28 UTC, oreocube approved these changes
고생하셨습니당

2023-05-24 17:28 UTC, oreocube commented on domain/src/main/java/com/mashup/alcoholfree/domain/usecase/AddTokenUseCase.kt
> +@Reusable
reusable은 언제 쓰는건가여??

2023-05-25 04:42 UTC, SEO-J17 commented on domain/src/main/java/com/mashup/alcoholfree/domain/usecase/AddTokenUseCase.kt
> +@Reusable
@oreocube 내가 알기론 싱글톤하고 반대 되는 개념으로 알고 있어

저 유스케이스가 사용이 끝나면 메모리에 유지되지 않고 바로 해제 되는 개념으로 알고 있어서, 유스케이스를 매번 사용할 때마다 값이 달라지기 때문에 Reusable로 작성했어! 

나도 딱 기본적인 것만 알고 있어서 맞는 대답인지는 몰겠다..ㅎㅎ 더 알아보고 말해줄겡ㅎ

2023-05-25 06:47 UTC, AnKyungMoo requested changes
누구보다 느리게 리뷰 남겨드렸습니다~

2023-05-25 06:47 UTC, AnKyungMoo commented on data/src/main/java/com/mashup/alcoholfree/data/repository/DataStoreRepositoryImpl.kt
> +) : DataStoreRepository {
```suggestion
class LoginRepositoryImpl @Inject constructor(
    private val dataStore: DataStore<Preferences>,
) : LoginRepository {
```
여기서 수행하는 역할은 로그인 관련인데 데이터스토어라고 되어있으면 나중에 서버랑 로그인 관련 로직을 수행할 때는 또 repository를 따로 만들어야할거같아
그것보다는 같은 기능을 하는거라면 하나의 repository에서 수행하는 것이 더 좋아보이네..!
어떻게 생각해?

2023-05-25 06:47 UTC, AnKyungMoo commented on domain/src/main/java/com/mashup/alcoholfree/domain/usecase/AddTokenUseCase.kt
> +@Reusable
Q: 그러면 Resuable을 사용하고 안하고의 차이가 뭐야?
값이 달라지는거면 어노테이션이 없어도 동일한거 아닌가??

2023-05-25 06:47 UTC, AnKyungMoo commented on domain/src/main/java/com/mashup/alcoholfree/domain/usecase/AddTokenUseCase.kt
> +    }
Result를 구분하도록 추후 개선하도록 하자. (지금 PR에는 적용하지 않아도 됨)

2023-05-25 06:47 UTC, AnKyungMoo commented on presentation/build.gradle.kts
> +
얘네 왜 추가한거야? 어디서 사용하고 있는건가연? 🧐🧐🧐

2023-05-25 06:47 UTC, AnKyungMoo commented on data/src/main/java/com/mashup/alcoholfree/data/di/DataStoreModule.kt
> +    fun providePreferencesDataStore(@ApplicationContext appContext: Context): DataStore<Preferences> {
```suggestion
    fun providePreferencesDataStore(@ApplicationContext context: Context): DataStore<Preferences> {
```

Nit: 꼭 applicationContext임을 알려주지 않아도 괜찮을거같아. 추가로 명시해주고싶다면 줄여쓰기보단 applicationContext로 풀어서 쓰는게 좋을거같아

2023-05-25 07:01 UTC, oreocube commented on presentation/build.gradle.kts
> +
HomeViewModel 만들어서 테스트할 때 넣어줬었어용

2023-05-25 07:12 UTC, AnKyungMoo commented on presentation/build.gradle.kts
> +
아~ 지금 사용되는게 아니라 테스트할 때 썼다는거구나
이거 우리 사용하게 될 디펜던신가?? (몰라서 물어봄)
컴포즈용 뷰모델이 무슨 용도로 사용되는지를 모르겠어서,,

2023-05-25 07:23 UTC, SEO-J17 commented on data/src/main/java/com/mashup/alcoholfree/data/repository/DataStoreRepositoryImpl.kt
> +) : DataStoreRepository {
@AnKyungMoo 훔 형님 그러면 데이터 스토어 로직을 사용하는 로그인이나 서버 관련 로직은 DataStoreRepositoryImpl에서 함수로 만들  유스케이스로 처리 가능할 거 같고, 나중에 로그인이 필요한 로직이 들어오게되면 그때 그거를 LoginRepository로 분리하는게 낫지 않나용?

2023-05-25 07:24 UTC, SEO-J17 commented on domain/src/main/java/com/mashup/alcoholfree/domain/usecase/AddTokenUseCase.kt
> +    }
넹넹

2023-05-25 07:25 UTC, SEO-J17 commented on presentation/build.gradle.kts
> +
넵 뷰모델 사용하게 될때 사용될거 같더라구요..? 이게 없으면 뷰모델 팩토리를 직접 구현해야 되는거 같더라구요..

2023-05-25 07:31 UTC, SEO-J17 commented on data/src/main/java/com/mashup/alcoholfree/data/di/DataStoreModule.kt
> +    fun providePreferencesDataStore(@ApplicationContext appContext: Context): DataStore<Preferences> {
넵넵 수정하는게 좋을것 같습니다!

2023-05-25 07:44 UTC, SEO-J17 commented on domain/src/main/java/com/mashup/alcoholfree/domain/usecase/AddTokenUseCase.kt
> +@Reusable
조금? 알아보니깐 만약 객체에 메모리에 있다면 재사용하고, 아니면 다시 생성해서 사용한다고 하네용 어떤 특정 컴포넌트 스코프에 종속되는게 아니라서 Resuable 어노테이션이 없어도 동일한 결과를 낼거 같습니다!

2023-05-25 08:37 UTC, oreocube commented on presentation/build.gradle.kts
> +
다시 생각해보니까 컴포저블에 인자로 뷰모델 넣으랴면 쟤네 의존성이 필요하고 
그게 아니라 액티비티에서 뷰모델 만들어서 컴포저블에는 인자로 값이랑 함수만 전달할거면 없어도 될 것 같긴하다 아니라면 패스

2023-05-25 08:42 UTC, SEO-J17 commented on presentation/build.gradle.kts
> +
만약 저게 없으면 뷰모델을 만들때  ' = viewModel() '이렇게 안되고 따로 구현해서 팩토리 넣어줘야 되는거 아니야? 그때 그래서 저거 의존성 추가하지 않았나..? 아니라면 패스ㅎ

2023-05-25 13:54 UTC, AnKyungMoo commented on data/src/main/java/com/mashup/alcoholfree/data/repository/DataStoreRepositoryImpl.kt
> +) : DataStoreRepository {
그렇다면 나는 datasource로 하나 더 분리하는게 좋을꺼같은데 이건 어떻게 생각해?

2023-05-26 13:50 UTC, AnKyungMoo commented on presentation/build.gradle.kts
> +
지혜가 말한거처럼 뷰모델 자체를 넘길건지, 아니면 필요한 상태랑 함수들만 따로 넘길건지에 대해서는 한 번 이야기해보면 좋을거같아

나는 개인적으로 뷰모델 자체를 넘기는쪽보다는 필요한 상태랑 함수들만 넘기는쪽으로 해보고싶다는 생각은 있어

2023-05-27 06:02 UTC, SEO-J17 commented on data/src/main/java/com/mashup/alcoholfree/data/repository/DataStoreRepositoryImpl.kt
> +) : DataStoreRepository {
넹넹 형님 그게 맞는거 같아요.. 제가 제 코드를 구현한 것과 다르게 생각하고 있었네용..ㅎ 수정하고 다시 request 하겠습니다!

2023-05-27 07:07 UTC, jisungbin commented on presentation/build.gradle.kts
> +
> 나는 개인적으로 뷰모델 자체를 넘기는쪽보다는 필요한 상태랑 함수들만 넘기는쪽으로 해보고싶다는 생각은 있어

그렇게 해야 리컴포지션 줄일 수 있어 (+ 권장 아키텍처이기도 해)

2023-05-28 08:34 UTC, AnKyungMoo approved these changes
LGTM! 고생하셧슴당

2023-05-29 10:43 UTC, merged